language: elixir
elixir:
  - 1.0.2
  - 1.0.3
  - 1.0.4
otp_release:
  - 17.4
sudo: false # to use faster container based build environment
script:
  - mix test
notifications:
  recipients:
    - johan@snowflake.nu
